spring:
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

api:
  url: https://api.apilayer.com/currency_data/live
  key: 5PVYUj2T4JuKj1eYwQtYA1AXItwYnBy9
